//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestAssure.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RestAssure.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advice.
        /// </summary>
        internal static string AdviceButton {
            get {
                return ResourceManager.GetString("AdviceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advice.
        /// </summary>
        internal static string AdviceTitle {
            get {
                return ResourceManager.GetString("AdviceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://nattarolabs.se/nattaro-en-bedbug-advice-tabell.
        /// </summary>
        internal static string AdviceUrl2 {
            get {
                return ResourceManager.GetString("AdviceUrl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nattaro Labs AB.
        /// </summary>
        internal static string AllCompanyName {
            get {
                return ResourceManager.GetString("AllCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string CameraButton {
            get {
                return ResourceManager.GetString("CameraButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No picture taken..
        /// </summary>
        internal static string CameraCancel {
            get {
                return ResourceManager.GetString("CameraCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click above to open camera and take a picture of a suspected bed bug. When you are done, press Send and attach the picture..
        /// </summary>
        internal static string CameraInstructions {
            get {
                return ResourceManager.GetString("CameraInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach a picture before sending, the picture you took last has been saved to the Camera Roll..
        /// </summary>
        internal static string CameraMailIntro {
            get {
                return ResourceManager.GetString("CameraMailIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedbug for Nattaro Labs.
        /// </summary>
        internal static string CameraMailSubject {
            get {
                return ResourceManager.GetString("CameraMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        internal static string CameraOpenButton {
            get {
                return ResourceManager.GetString("CameraOpenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string CameraSendButton {
            get {
                return ResourceManager.GetString("CameraSendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string CameraTitle {
            get {
                return ResourceManager.GetString("CameraTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string ContactButton {
            get {
                return ResourceManager.GetString("ContactButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question for Nattaro Labs.
        /// </summary>
        internal static string ContactMailSubject {
            get {
                return ResourceManager.GetString("ContactMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestAssure (v{0}) is developed and published by Nattaro Labs AB, experts on bedbugs, in close collaboration with Dahlman Software Science AB, Dahlman Labs and Gabriel Lundh Design. .
        /// </summary>
        internal static string ContactPage_Line1 {
            get {
                return ResourceManager.GetString("ContactPage_Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our intention with this mobile application is to provide you with a tool to prevent a bedbug infestation and advice for you who has already been affected by this annoyance. .
        /// </summary>
        internal static string ContactPage_Line2 {
            get {
                return ResourceManager.GetString("ContactPage_Line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to find out more about our products please visit nattarolabs.se. .
        /// </summary>
        internal static string ContactPage_Line3 {
            get {
                return ResourceManager.GetString("ContactPage_Line3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not hesitate to mail us your suggestions on how we can make RestAssure even better. .
        /// </summary>
        internal static string ContactPage_Line4 {
            get {
                return ResourceManager.GetString("ContactPage_Line4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ContactPage_Line5 {
            get {
                return ResourceManager.GetString("ContactPage_Line5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2015 Nattaro Labs AB.
        /// </summary>
        internal static string ContactPage_Line6 {
            get {
                return ResourceManager.GetString("ContactPage_Line6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string ContactTitle {
            get {
                return ResourceManager.GetString("ContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facts.
        /// </summary>
        internal static string FactsButton {
            get {
                return ResourceManager.GetString("FactsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facts.
        /// </summary>
        internal static string FactsTitle {
            get {
                return ResourceManager.GetString("FactsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://nattarolabs.se/nattaro-en-bedbug-facts-tabell.
        /// </summary>
        internal static string FactsUrl2 {
            get {
                return ResourceManager.GetString("FactsUrl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Loading1 {
            get {
                return ResourceManager.GetString("Loading1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string Loading2 {
            get {
                return ResourceManager.GetString("Loading2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network problem.
        /// </summary>
        internal static string LoadingProblem1 {
            get {
                return ResourceManager.GetString("LoadingProblem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait or try again....
        /// </summary>
        internal static string LoadingProblem2 {
            get {
                return ResourceManager.GetString("LoadingProblem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent from the RestAssure WP8-App.
        /// </summary>
        internal static string MailFooter {
            get {
                return ResourceManager.GetString("MailFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;p&gt;$_Section:Bedbug advice (offline);&lt;/p&gt;
        ///&lt;p&gt;$_Item:General advice while on journey;&lt;/p&gt;
        ///&lt;p&gt;$_Thumbnail:&lt;img src=&quot;res://images/T/APP020T_72.png&quot; alt=&quot;&quot; width=&quot;68&quot; height=&quot;68&quot; /&gt;&lt;/p&gt;
        ///&lt;p&gt;$_Link:&lt;a title=&quot;Item1&quot; href=&quot;res://pages/nattaro-en-bedbug-advice.html#Advice%201__advice1&quot;&gt;Link&lt;/a&gt;&lt;/p&gt;
        ///&lt;p&gt;$_Item:Before the trip;&lt;/p&gt;
        ///&lt;p&gt;$_Thumbnail:&lt;img src=&quot;res://images/T/APP012T_72.png&quot; alt=&quot;&quot; width=&quot;68&quot; height=&quot;68&quot; /&gt;&lt;/p&gt;
        ///&lt;p&gt;$_Link:&lt;a title=&quot;Item1&quot; href=&quot;res://pages/nattaro-en-be [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OfflineAdviceMenu {
            get {
                return ResourceManager.GetString("OfflineAdviceMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;p&gt;$_Section:Facts about bedbugs (offline);&lt;/p&gt;
        ///&lt;p&gt;$_Item:Biology;&lt;/p&gt;
        ///&lt;p&gt;$_Thumbnail:&lt;img src=&quot;res://Images/T/APP002T_72.png&quot; width=&quot;68&quot; height=&quot;68&quot;&gt;&lt;/img&gt;&lt;/p&gt;
        ///&lt;p&gt;$_Link:&lt;a title=&quot;Item1&quot; href=&quot;res://Pages/nattaro-en-bedbug-facts.html#Fact%201__fact1&quot;&gt;Link&lt;/a&gt;&lt;/p&gt;
        ///&lt;p&gt;$_Item:Historic names;&lt;/p&gt;
        ///&lt;p&gt;$_Thumbnail:&lt;img src=&quot;res://Images/T/APP003T_72.png&quot; width=&quot;68&quot; height=&quot;68&quot;&gt;&lt;/img&gt;&lt;/p&gt;
        ///&lt;p&gt;$_Link:&lt;a title=&quot;Item1&quot; href=&quot;res://Pages/nattaro-en-bedbug-facts.html#Fact%202__fact [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OfflineFactsMenu {
            get {
                return ResourceManager.GetString("OfflineFactsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestAssure.
        /// </summary>
        internal static string StartPageTitle {
            get {
                return ResourceManager.GetString("StartPageTitle", resourceCulture);
            }
        }
    }
}
